#Robocode window sizes
#Sun Jun 22 19:23:24 BRT 2025
net.sf.robocode.ui.dialog.NewBattleDialog=38,25,850,650
net.sf.robocode.ui.dialog.ConsoleDialog=518,231,500,400
net.sf.robocode.ui.dialog.RobocodeFrame=0,0,927,701
net.sf.robocode.ui.editor.RobocodeEditor=386,126,764,611
